"""World tuning — edit difficulty here."""

SCENE_ID = "gigas_clearing"

# 原著向：巨树血量可完成章节剧情，3天砍树+NPC贡献约150-200伤害。
TREE_HP_MAX = 200
CHOP_DAMAGE = 10
CHOP_STAMINA_COST = 8

STAMINA_MAX = 100
REST_RECOVER = 22

HUNGER_MAX = 100
HUNGER_INCREASE = 1
EAT_STAMINA_RECOVER = 10
EAT_HUNGER_DECREASE = 30
SLEEP_STAMINA_RECOVER = 50
SLEEP_HUNGER_INCREASE = 10

# 单日共 TICK_PER_DAY 个「时刻」：tick 取 0..TICK_LAST_IN_DAY，下一次 advance 后若 >= TICK_PER_DAY 则归零并进日。
TICK_PER_DAY = 61
TICK_LAST_IN_DAY = TICK_PER_DAY - 1

# 昼夜分界（上界为开区间，与 time_bands.circadian_hint_zh 一致）
CIRCADIAN_MORNING_END = 15
CIRCADIAN_AFTERNOON_END = 40
CIRCADIAN_EVENING_END = 52

MEAL_TICK = 30

RECENT_EVENTS_K = 12

REAL_SECONDS_PER_HOUR = 10
REAL_SECONDS_PER_TICK = REAL_SECONDS_PER_HOUR / 24
